services:
  api:
    build:
      context: ./fastapi_code
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: fastapi_api
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+psycopg://postgres:postgres@db:5432/listening
      YOUTUBE_API_KEY: ${YOUTUBE_API_KEY}

  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_DB: listening
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

volumes:
  pgdata: